import { state } from "../state/state.js";
import { buildKeyframesFromStep } from "../preview/previewEngine.js";


export function generateCodeFromTimeline(element) {
 
  element.textContent = "";
  const steps = state.steps;
  const lines = [];

  lines.push(`// Generated by Motion Builder JS`);
  lines.push(`// Paste this into your project and replace "element" with your own target element.`);
  lines.push("");

  lines.push(`const element = document.querySelector("#your-element");`);
  lines.push("");

  lines.push(`const timeline = [`);

  steps.forEach((step, index) => {
    const [fromFrame, toFrame] = buildKeyframesFromStep(step);

    lines.push(`  {`);
    lines.push(`    duration: ${step.duration},`);
    lines.push(`    easing: "${step.easing}",`);
    lines.push(`    from: ${JSON.stringify(fromFrame)},`);
    lines.push(`    to:   ${JSON.stringify(toFrame)}`);
    lines.push(`  }${index < steps.length - 1 ? "," : ""}`);
  });

  lines.push(`];`);
  lines.push("");
  lines.push(`// To run:`);
  lines.push(`// playTimeline(element, timeline);`);

  element.textContent = lines.join("\n");
}
